language: python
services: memcached
sudo: false

matrix:
  include:
  - python: "3.6"  
    env: TOX_ENV=py36-django22
    dist: xenial
  - python: "3.7"
    env: TOX_ENV=py37-django30
    dist: xenial
  - python: "3.7"
    env: TOX_ENV=py37-django31
    dist: xenial
  - python: "3.6"
    env: TOX_ENV=py36-django22-jinja2
  - python: "3.6"
    env: TOX_ENV=flake8
  - python: "3.6"
    env: TOX_ENV=gettext

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
